name: Transition issue to In Review

on:
  pull_request:
    types:
      - assigned

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "In review"
        env:
          ASSIGNEE_ID: ${{ github.event.pull_request.body }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "here we go"; echo '${{ toJson(github.event.pull_request) }}'
