name: Transition issue to In Review

on:
  pull_request:
    types:
      - assigned

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue info from pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api graphql -f query='
            query {
              node(id: "${{ github.event.pull_request.node_id }}") {
                ... on PullRequest {
                  closingIssuesReferences(first: 1) {
                    nodes {
                      id
                      title
                    }
                  }
                }
              }
            }
          ' > issue_info.json
          echo 'ISSUE_ID='$(jq '.data.node.closingIssuesReferences.nodes[0].id' issue_info.json) >> $GITHUB_ENV

      - name: Assign issue to PR assignee
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api graphql -f query='
            mutation($issueId: ID!) {
              updateIssue(input: {id: "$($issueId)", assigneeIds: [ ${{ github.event.pull_request.assignee.id }} ]}) {
                clientMutationId
              }
            }
          ' -f issueId=$ISSUE_ID
