name: Transition issue to In Review

on:
  pull_request:
    types:
      - assigned

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "In review"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'github.repository_owner:'
          echo '${{ github.repository_owner }}'
          echo 'github.event.repository:'
          echo '${{ toJson(github.event.repository) }}'
          echo 'github.event.pull_request:'
          echo '${{ toJson(github.event.pull_request) }}'
